package simula.lexer;

import com.intellij.psi.tree.IElementType;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;
import simula.lang.SimulaLanguage;

public class KeyWordToken extends IElementType {
	private KeyWordToken(@NonNls @NotNull String debugName) { super(debugName, SimulaLanguage.INSTANCE);	}

	/** Simula Keyword */ public static final KeyWordToken ACTIVATE     = new KeyWordToken("ACTIVATE");
	/** Simula Keyword */ public static final KeyWordToken AND          = new KeyWordToken("AND");
	/** Simula Keyword */ public static final KeyWordToken AND_THEN     = new KeyWordToken("AND_THEN");
	/** Simula Keyword */ public static final KeyWordToken AFTER        = new KeyWordToken("AFTER");
	/** Simula Keyword */ public static final KeyWordToken ARRAY        = new KeyWordToken("ARRAY");
	/** Simula Keyword */ public static final KeyWordToken AT           = new KeyWordToken("AT");
	/** Simula Keyword */ public static final KeyWordToken BEFORE       = new KeyWordToken("BEFORE");
	/** Simula Keyword */ public static final KeyWordToken BEGIN        = new KeyWordToken("BEGIN");
	/** Simula Keyword */ public static final KeyWordToken BOOLEAN      = new KeyWordToken("BOOLEAN");
	/** Simula Keyword */ public static final KeyWordToken CHARACTER    = new KeyWordToken("CHARACTER");
	/** Simula Keyword */ public static final KeyWordToken CLASS        = new KeyWordToken("CLASS");
	/** Simula Keyword */ public static final KeyWordToken COMMENT      = new KeyWordToken("COMMENT");
	/** Simula Keyword */ public static final KeyWordToken CONC         = new KeyWordToken("CONC");
	/** Simula Keyword */ public static final KeyWordToken DELAY        = new KeyWordToken("DELAY");
	/** Simula Keyword */ public static final KeyWordToken DO           = new KeyWordToken("DO");
	/** Simula Keyword */ public static final KeyWordToken ELSE         = new KeyWordToken("ELSE");
	/** Simula Keyword */ public static final KeyWordToken END          = new KeyWordToken("END");
	/** Simula Keyword */ public static final KeyWordToken EQ           = new KeyWordToken("EQ");
	/** Simula Keyword */ public static final KeyWordToken EQV          = new KeyWordToken("EQV");
	/** Simula Keyword */ public static final KeyWordToken EXTERNAL     = new KeyWordToken("EXTERNAL");
	/** Simula Keyword */ public static final KeyWordToken FALSE        = new KeyWordToken("FALSE");
	/** Simula Keyword */ public static final KeyWordToken FOR          = new KeyWordToken("FOR");
	/** Simula Keyword */ public static final KeyWordToken GE           = new KeyWordToken("GE");
	/** Simula Keyword */ public static final KeyWordToken GO           = new KeyWordToken("GO");
	/** Simula Keyword */ public static final KeyWordToken GOTO         = new KeyWordToken("GOTO");
	/** Simula Keyword */ public static final KeyWordToken GT           = new KeyWordToken("GT");
	/** Simula Keyword */ public static final KeyWordToken HIDDEN       = new KeyWordToken("HIDDEN");
	/** Simula Keyword */ public static final KeyWordToken IF           = new KeyWordToken("IF");
	/** Simula Keyword */ public static final KeyWordToken IMP          = new KeyWordToken("IMP");
	/** Simula Keyword */ public static final KeyWordToken IN           = new KeyWordToken("IN");
	/** Simula Keyword */ public static final KeyWordToken INNER        = new KeyWordToken("INNER");
	/** Simula Keyword */ public static final KeyWordToken INSPECT      = new KeyWordToken("INSPECT");
	/** Simula Keyword */ public static final KeyWordToken INTEGER      = new KeyWordToken("INTEGER");
	/** Simula Keyword */ public static final KeyWordToken IS           = new KeyWordToken("IS");
	/** Simula Keyword */ public static final KeyWordToken LABEL        = new KeyWordToken("LABEL");
	/** Simula Keyword */ public static final KeyWordToken LE           = new KeyWordToken("LE");
	/** Simula Keyword */ public static final KeyWordToken LONG         = new KeyWordToken("LONG");
	/** Simula Keyword */ public static final KeyWordToken LT           = new KeyWordToken("LT");
	/** Simula Keyword */ public static final KeyWordToken NAME         = new KeyWordToken("NAME");
	/** Simula Keyword */ public static final KeyWordToken NE           = new KeyWordToken("NE");
	/** Simula Keyword */ public static final KeyWordToken NEW          = new KeyWordToken("NEW");
	/** Simula Keyword */ public static final KeyWordToken NONE         = new KeyWordToken("NONE");
	/** Simula Keyword */ public static final KeyWordToken NOT          = new KeyWordToken("NOT");
	/** Simula Keyword */ public static final KeyWordToken NOTEXT       = new KeyWordToken("NOTEXT");
	/** Simula Keyword */ public static final KeyWordToken OR           = new KeyWordToken("OR");
	/** Simula Keyword */ public static final KeyWordToken OR_ELSE      = new KeyWordToken("OR_ELSE");
	/** Simula Keyword */ public static final KeyWordToken OTHERWISE    = new KeyWordToken("OTHERWISE");
	/** Simula Keyword */ public static final KeyWordToken PRIOR        = new KeyWordToken("PRIOR");
	/** Simula Keyword */ public static final KeyWordToken PROCEDURE    = new KeyWordToken("PROCEDURE");
	/** Simula Keyword */ public static final KeyWordToken PROTECTED    = new KeyWordToken("PROTECTED");
	/** Simula Keyword */ public static final KeyWordToken QUA          = new KeyWordToken("QUA");
	/** Simula Keyword */ public static final KeyWordToken REACTIVATE   = new KeyWordToken("REACTIVATE");
	/** Simula Keyword */ public static final KeyWordToken REAL         = new KeyWordToken("REAL");
	/** Simula Keyword */ public static final KeyWordToken REF          = new KeyWordToken("REF");
	/** Simula Keyword */ public static final KeyWordToken SHORT        = new KeyWordToken("SHORT");
	/** Simula Keyword */ public static final KeyWordToken STEP         = new KeyWordToken("STEP");
	/** Simula Keyword */ public static final KeyWordToken SWITCH       = new KeyWordToken("SWITCH");
	/** Simula Keyword */ public static final KeyWordToken TEXT         = new KeyWordToken("TEXT");
	/** Simula Keyword */ public static final KeyWordToken THEN         = new KeyWordToken("THEN");
	/** Simula Keyword */ public static final KeyWordToken THIS         = new KeyWordToken("THIS");
	/** Simula Keyword */ public static final KeyWordToken TO           = new KeyWordToken("TO");
	/** Simula Keyword */ public static final KeyWordToken TRUE         = new KeyWordToken("TRUE");
	/** Simula Keyword */ public static final KeyWordToken UNTIL        = new KeyWordToken("UNTIL");
	/** Simula Keyword */ public static final KeyWordToken VALUE        = new KeyWordToken("VALUE");
	/** Simula Keyword */ public static final KeyWordToken VIRTUAL      = new KeyWordToken("VIRTUAL");
	/** Simula Keyword */ public static final KeyWordToken WHEN         = new KeyWordToken("WHEN");
	/** Simula Keyword */ public static final KeyWordToken WHILE        = new KeyWordToken("WHILE");
	// Other Symbols
	/** Other Symbol */ public static final KeyWordToken ASSIGNVALUE    = new KeyWordToken("ASSIGNVALUE");
	/** Other Symbol */ public static final KeyWordToken ASSIGNREF      = new KeyWordToken("ASSIGNREF");
	/** Other Symbol */ public static final KeyWordToken COMMA          = new KeyWordToken("COMMA");
	/** Other Symbol */ public static final KeyWordToken COLON          = new KeyWordToken("COLON");
	/** Other Symbol */ public static final KeyWordToken SEMICOLON      = new KeyWordToken("SEMICOLON");
	/** Other Symbol */ public static final KeyWordToken BEGPAR         = new KeyWordToken("BEGPAR");
	/** Other Symbol */ public static final KeyWordToken ENDPAR         = new KeyWordToken("ENDPAR");
	/** Other Symbol */ public static final KeyWordToken BEGBRACKET     = new KeyWordToken("BEGBRACKET");
	/** Other Symbol */ public static final KeyWordToken ENDBRACKET     = new KeyWordToken("ENDBRACKET");
	/** Other Symbol */ public static final KeyWordToken EQR            = new KeyWordToken("EQR");
	/** Other Symbol */ public static final KeyWordToken NER            = new KeyWordToken("NER");
	/** Other Symbol */ public static final KeyWordToken PLUS           = new KeyWordToken("PLUS");
	/** Other Symbol */ public static final KeyWordToken MINUS          = new KeyWordToken("MINUS");
	/** Other Symbol */ public static final KeyWordToken MUL            = new KeyWordToken("MUL");
	/** Other Symbol */ public static final KeyWordToken DIV            = new KeyWordToken("DIV");
	/** Other Symbol */ public static final KeyWordToken INTDIV         = new KeyWordToken("INTDIV");
	/** Other Symbol */ public static final KeyWordToken EXP            = new KeyWordToken("EXP");
	/** Other Symbol */ public static final KeyWordToken AMPERSAND      = new KeyWordToken("AMPERSAND");
//	/** Other Symbol */ public static final KeyWord IDENTIFIER     = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord BOOLEANKONST   = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord INTEGERKONST   = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord CHARACTERKONST = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord REALKONST      = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord TEXTKONST      = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord OR_ELSE        = new KeyWord("");
//	/** Other Symbol */ public static final KeyWord AND_THEN       = new KeyWord("");
	/** Other Symbol */ public static final KeyWordToken DOT            = new KeyWordToken(".");
	/** Other Symbol */ public static final KeyWordToken NEWLINE        = new KeyWordToken("NEWLINE");
	/** Other Symbol */ public static final KeyWordToken STRING         = new KeyWordToken("STRING");
	/** Other Symbol */ public static final KeyWordToken EOF	           = new KeyWordToken("EOF");

}
