package simula.parser;

import com.intellij.lang.ASTNode;
import com.intellij.lang.ParserDefinition;
import com.intellij.lang.PsiParser;
import com.intellij.lexer.Lexer;
import com.intellij.openapi.project.Project;
import com.intellij.psi.FileViewProvider;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiFile;
import com.intellij.psi.tree.IFileElementType;
import com.intellij.psi.tree.TokenSet;

import simula.lexer.SimulaLexer;
import simula.lang.SimulaLanguage;
import simula.lang.SimulaLanguageFile;
import simula.lang.SimulaTokenSets;

public class SimulaParserDefinition implements ParserDefinition {

    
    // In the IntelliJ Platform SDK,
    // the ParserDefinition.createFile() method is the factory method responsible
    // for creating the PSI (Program Structure Interface) root for a specific file type.
    // This root element must implement the PsiFile interface.
    //
    // PSI Lifecycle: The createFile method is called by the IDE whenever it needs to build a PSI tree for a file of your registered language.
    // Relationship with AST: The PsiFile created here will eventually contain the full PSI tree built on top of the AST nodes generated by your PsiParser.
    public PsiFile createFile(FileViewProvider fileViewProvider) {
        System.out.println("SimulaParserDefinition.createFile was called: fileViewProvider=" + fileViewProvider);
//        if(true) throw new RuntimeException("SimulaParserDefinition.createFile was called: fileViewProvider=" + fileViewProvider);
        return new SimulaLanguageFile(fileViewProvider);
//        return null;
    }

    
    // createLexer(Project project): Returns the lexer for your language.
    public Lexer createLexer(Project project) {
        System.out.println("SimulaParserDefinition.createLexer was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.createLexer was called");
        Lexer lexer = new SimulaLexer();
        return lexer;
    }

    
    // createParser(Project project): Returns your custom PsiParser implementation.
    public PsiParser createParser(Project project) {
        System.out.println("SimulaParserDefinition.createParser was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.createParser was called");
        PsiParser parser = new SimulaParser();
        return parser;
    }

    // 1. Define the file node type as a static constant
    public static final IFileElementType SIMULA_FILE = new IFileElementType(SimulaLanguage.INSTANCE);

    
    // getFileNodeType(): Returns the IFileElementType for the root of your PSI tree.
    public IFileElementType getFileNodeType() {
        System.out.println("SimulaParserDefinition.getFileNodeType was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.getFileNodeType was called");
        return SIMULA_FILE;
    }

    public TokenSet getCommentTokens() {
        System.out.println("SimulaParserDefinition.getCommentTokens was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.getCommentTokens was called");
        return SimulaTokenSets.COMMENTS;
    }

    public TokenSet getStringLiteralElements() {
        if(true) throw new RuntimeException("SimulaParserDefinition.getStringLiteralElements was called");
        return null;
    }

    
    // createElement(ASTNode node): Acts as a factory to create PSI elements from AST nodes.
    public PsiElement createElement(ASTNode astNode) {
        if(true) throw new RuntimeException("SimulaParserDefinition.createElement was called");
        return null;
    }


}
