package simula.lang;

import com.intellij.lang.*;
import com.intellij.lang.impl.PsiBuilderImpl;
import com.intellij.lexer.Lexer;
import com.intellij.openapi.extensions.BaseExtensionPointName;
import com.intellij.openapi.extensions.ExtensionPoint;
import com.intellij.openapi.extensions.ExtensionPointName;
import com.intellij.openapi.progress.ProgressManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.KeyedExtensionCollector;
import com.intellij.openapi.vfs.VirtualFileManager;
import com.intellij.platform.syntax.impl.builder.MarkerOptionalData;
import com.intellij.psi.FileViewProvider;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiFile;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.tree.IFileElementType;
import com.intellij.psi.tree.TokenSet;
import com.intellij.testFramework.ParsingTestCase;
import com.intellij.testFramework.UsefulTestCase;
import com.intellij.util.Functions;
import com.intellij.util.containers.ContainerUtil;
import com.intellij.util.messages.MessageBusConnection;
import com.intellij.util.xmlb.annotations.Transient;
import it.unimi.dsi.fastutil.ints.Int2ObjectFunction;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.*;
import org.intellij.lang.annotations.MagicConstant;
import org.jetbrains.annotations.NotNull;
import simula.lexer.SimulaLexer;

public class SimulaParserDefinition implements ParserDefinition {
    BaseExtensionPointName
    xxx;
    @Override
    // In the IntelliJ Platform SDK,
    // the ParserDefinition.createFile() method is the factory method responsible
    // for creating the PSI (Program Structure Interface) root for a specific file type.
    // This root element must implement the PsiFile interface.
    //
    // PSI Lifecycle: The createFile method is called by the IDE whenever it needs to build a PSI tree for a file of your registered language.
    // Relationship with AST: The PsiFile created here will eventually contain the full PSI tree built on top of the AST nodes generated by your PsiParser.
    public @NotNull PsiFile createFile(@NotNull FileViewProvider fileViewProvider) {
        System.out.println("SimulaParserDefinition.createFile was called: fileViewProvider=" + fileViewProvider);
//        if(true) throw new RuntimeException("SimulaParserDefinition.createFile was called: fileViewProvider=" + fileViewProvider);
        return new SimulaLanguageFile(fileViewProvider);
//        return null;
    }

    @Override
    // createLexer(Project project): Returns the lexer for your language.
    public @NotNull Lexer createLexer(Project project) {
        System.out.println("SimulaParserDefinition.createLexer was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.createLexer was called");
        Lexer lexer = new SimulaLexer();
        return lexer;
    }

    @Override
    // createParser(Project project): Returns your custom PsiParser implementation.
    public @NotNull PsiParser createParser(Project project) {
        System.out.println("SimulaParserDefinition.createParser was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.createParser was called");
        PsiParser parser = new SimulaParser();
        return parser;
    }

    // 1. Define the file node type as a static constant
    public static final IFileElementType SIMULA_FILE = new IFileElementType(SimulaLanguage.INSTANCE);

    @Override
    // getFileNodeType(): Returns the IFileElementType for the root of your PSI tree.
    public @NotNull IFileElementType getFileNodeType() {
        System.out.println("SimulaParserDefinition.getFileNodeType was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.getFileNodeType was called");
        return SIMULA_FILE;
    }

    @Override
    public @NotNull TokenSet getCommentTokens() {
        System.out.println("SimulaParserDefinition.getCommentTokens was called");
//        if(true) throw new RuntimeException("SimulaParserDefinition.getCommentTokens was called");
        return SimulaTokenSets.COMMENTS;
    }

    @Override
    public @NotNull TokenSet getStringLiteralElements() {
        if(true) throw new RuntimeException("SimulaParserDefinition.getStringLiteralElements was called");
        return null;
    }

    @Override
    // createElement(ASTNode node): Acts as a factory to create PSI elements from AST nodes.
    public @NotNull PsiElement createElement(ASTNode astNode) {
        if(true) throw new RuntimeException("SimulaParserDefinition.createElement was called");
        return null;
    }
}
